---
version: "2"
services:
  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: ./cmd/web/Dockerfile
    image: web
    ports:
      - "8080:8080"
    environment:
      - ADDR=0.0.0.0:8080
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: ./cmd/worker/Dockerfile
    image: worker
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis