---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: worker
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_ADDR
              value: "redis:6379"
